const constants = {
  ADMIN_UPLOAD_IMG_QTY: 10,
  PARTNER_UPLOAD_IMG_QTY: 5,
  MARKET_UPLOAD_IMG_QTY: 2,
  ADMIN_UPLOAD_IMG_SIZE: 10240,
  PARTNER_UPLOAD_IMG_SIZE: 3072,
  AVATAR_UPLOAD_IMG_SIZE: 2048,
  CATEGORY_UPLOAD_IMG_SIZE: 3072,
  BANNER_UPLOAD_IMG_SIZE: 3072,
  BRAND_UPLOAD_IMG_SIZE: 3072,
  SINGLE_UPLOAD_FIELD_NAME: 'image',
  ARRAY_UPLOAD_FIELD_NAME: 'images'
}

module.exports = constants
